web_panel/src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: AccountRepository::class)]
#[UniqueEntity(
    fields: ['login'],
    errorPath: 'app_account_create',
    message: 'This login is already in use.',
)]
class Account
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $login = null;

    #[ORM\Column(length: 1000)]
    private ?string $password = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $cookies = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $event = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Date = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode1 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode2 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $Price = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode3 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode4 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Seats = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Price2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Seats2 = null;

    #[ORM\Column(length: 255, options: ["default" => 'Active'], nullable: true)]
    private ?string $status = null;

    #[ORM\Column(nullable: true)]
    private ?int $worker_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): static
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getCookies(): ?string
    {
        return $this->cookies;
    }

    public function setCookies(string $cookies): static
    {
        $this->cookies = $cookies;

        return $this;
    }

    public function getEvent(): ?string
    {
        return $this->event;
    }

    public function setEvent(string $event): static
    {
        $this->event = $event;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(?string $Date): static
    {
        $this->Date = $Date;

        return $this;
    }

    public function getBarcode1(): ?string
    {
        return $this->barcode1;
    }

    public function setBarcode1(?string $barcode1): static
    {
        $this->barcode1 = $barcode1;

        return $this;
    }

    public function getBarcode2(): ?string
    {
        return $this->barcode2;
    }

    public function setBarcode2(?string $barcode2): static
    {
        $this->barcode2 = $barcode2;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(?string $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getBarcode3(): ?string
    {
        return $this->barcode3;
    }

    public function setBarcode3(?string $barcode3): static
    {
        $this->barcode3 = $barcode3;

        return $this;
    }

    public function getBarcode4(): ?string
    {
        return $this->barcode4;
    }

    public function setBarcode4(?string $barcode4): static
    {
        $this->barcode4 = $barcode4;

        return $this;
    }

    public function getSeats(): ?string
    {
        return $this->Seats;
    }

    public function setSeats(?string $Seats): static
    {
        $this->Seats = $Seats;

        return $this;
    }

    public function getPrice2(): ?string
    {
        return $this->Price2;
    }

    public function setPrice2(?string $Price2): static
    {
        $this->Price2 = $Price2;

        return $this;
    }

    public function getSeats2(): ?string
    {
        return $this->Seats2;
    }

    public function setSeats2(?string $Seats2): static
    {
        $this->Seats2 = $Seats2;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getWorkerId(): ?int
    {
        return $this->worker_id;
    }

    public function setWorkerId(?int $worker_id): static
    {
        $this->worker_id = $worker_id;

        return $this;
    }
}

web_panel/src/Controller/MainWorkPageController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\News;
use App\Repository\NewsRepository;
 

class MainWorkPageController extends AbstractController
{
    #[Route('/home', name: 'app_main_work_page')]
    public function index(NewsRepository $news_repository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            // Handle the case where there's no authenticated user
            return $this->redirectToRoute('login'); // Or handle it differently
        }

         

        // Query to fetch the entity with type "Admin Message" and the highest ID along with the "Text" parameter
        $adminMessage = $news_repository->GetLastAdminMessage();

        $events = $news_repository->GetLastEventMessage();
         

        $news  = ['admin'=> $adminMessage, 'events' => $events];
        return $this->render('main_work_page/index.html.twig', [
            'controller_name' => 'MainWorkPageController',
            'user' => $user,
            'news' =>  $news
        ]);
    }
}

web_panel/templates/main_work_page/account.html.twig
 {% extends "main_work_page/navigation_panel.html.twig" %}
 {% block title %}Web panel{% endblock %}

{% block head %} {{parent()}} {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full flex flex-col h-screen overflow-y-hidden">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
            {% for flash_type, messages in app.flashes %}
                                    {% for message in messages %}
                                    
                                        {% if flash_type =='error' %}
                                            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                                                    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                                    </svg>
                                                    <span class="sr-only">Info</span>
                                                    <div>
                                                        <span class="font-medium">&nbsp;&nbsp;Error.&nbsp;</span> {{ message }}
                                                    </div>
                                                    </div>
                                        {% else %}
                                          <div class="flex items-center p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                        </svg>
                                        <span class="sr-only">Info</span>
                                        <div>
                                            <span class="font-medium">Success!</span> {{ message }}
                                        </div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
        <div class="w-full overflow-x-hidden border-t flex flex-col">
               <main class="w-full flex-grow p-6">

                    <div class="w-full mt-12">
                    <p class="text-xl pb-3 flex items-center">
                           <i class="fas fa-list mr-3"></i> Accounts
                    </p>
                  
                         <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                            <a href="{{ path('app_account_create') }}"><i class="fas fa-plus mr-3"></i> Add account </a>
                        </button>
                    <div class="bg-white overflow-auto">
                        <table class="text-left w-full border-collapse"> <!--Border collapse doesn't work on this site yet but it's available in newer tailwind versions -->
                            <thead>
                                <tr>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Login</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Password</th>
                                     
                                </tr>
                            </thead>
                            <tbody>
                                        {% for account in accounts %}
                                            <tr class="hover:bg-grey-lighter">
                                                <td class="py-4 px-6 border-b border-grey-light">{{ account.login }}</td>
                                                <td class="py-4 px-6 border-b border-grey-light">{{ account.password }}</td>
                                                <td class="py-4 px-6 border-b border-grey-light">
                                                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                                                        <a href="{{ path('app_logged_account',{'id': account.id }) }}"> <i class="fas fa-sign-in-alt mr-3"></i> Get Account ! </a>
                                                    </button>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                 
                            </tbody>
                        </table>
                    </div>

               </main>
    
            <footer class="w-full bg-white text-right p-4">
                By ANCIENT STUDIO
            </footer>
        </div>
        
    </div>
    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
     
     
</body>
</html>
        {% endblock %}
         

     

 

web_panel/templates/main_work_page/account_create.html.twig
 {% extends "main_work_page/navigation_panel.html.twig" %}
 {% block title %}Web panel{% endblock %}

{% block head %} {{parent()}} {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full flex flex-col h-screen overflow-y-hidden">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
            
             {% for flash_type, messages in app.flashes %}
                                    {% for message in messages %}
                                    
                                        {% if flash_type =='error' %}
                                            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                                                    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                                    </svg>
                                                    <span class="sr-only">Info</span>
                                                    <div>
                                                        <span class="font-medium">&nbsp;&nbsp;Error.&nbsp;</span> {{ message }}
                                                    </div>
                                                    </div>
                                        {% else %}
                                         <div class="flex items-center p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                        </svg>
                                        <span class="sr-only">Info</span>
                                        <div>
                                            <span class="font-medium">Success!</span> {{ message }}
                                        </div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
        <div class="w-full overflow-x-hidden border-t flex flex-col">
          
                <main class="w-full flex-grow p-6">
                <div class="w-full lg:w-1/2 my-6 pr-0 lg:pr-2">
                
                               
                                <p class="text-xl pb-6 flex items-center">
                                    <i class="fas fa-list mr-3"></i>Add new account
                                </p>
                        <div class="leading-loose">
                            
                                 {{ form_start(form, {'attr': {'class' : 'p-10 bg-white rounded shadow-xl' }}) }}
                                  {{ form_widget(form.login) }}
                                <div class="mt-2">
                                     
                                   {{ form_row(form.password) }}
                                </div>
                               <div class="mt-6">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Create</button>
                                </div>
                                   {{ form_end(form) }}
                       
                    </div>
                </div>
                </main>
            <footer class="w-full bg-white text-right p-4">
                By ANCIENT STUDIO
            </footer>
        </div>
        
    </div>
    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
     
     
</body>
</html>
        {% endblock %}
         

     

 

web_panel/templates/main_work_page/create_news.html.twig
{% extends "main_work_page/navigation_panel.html.twig" %}

{% block title %}Edit...{% endblock %}

{% block head %} {{parent()}} {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full flex flex-col h-screen overflow-y-hidden">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
        <main class="w-full flex-grow p-6">
        <div class="w-full lg:w-1/2 my-6 pr-0 lg:pr-2">
                        <p class="text-xl pb-6 flex items-center">
                            <i class="fas fa-list mr-3"></i> Edit {{ type }}
                        </p>
                        <div class="leading-loose">
                            
                                 {{ form_start(form, {'attr': {'class' : 'p-10 bg-white rounded shadow-xl' }}) }}
                                  {{ form_widget(form.type, {'attr' : {'hidden':''}}) }}
                                <div class="mt-2">
                                     
                                   {{ form_row(form.text) }}
                                </div>
                                <div class="mt-6">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Submit</button>
                                </div>
                </form>
            </div>
        </div>
        </main>
     <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <!-- ChartJS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>

 
   
{% endblock %}

web_panel/templates/main_work_page/logged_account.html.twig
 {% extends "main_work_page/navigation_panel.html.twig" %}
 {% block title %}Web panel{% endblock %}

{% block head %} {{parent()}} {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full flex flex-col h-screen overflow-y-hidden">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
             {% for flash_type, messages in app.flashes %}
                                    {% for message in messages %}
                                    
                                        {% if flash_type =='error' %}
                                            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                                                    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                                    </svg>
                                                    <span class="sr-only">Info</span>
                                                    <div>
                                                        <span class="font-medium">&nbsp;&nbsp;Error.&nbsp;</span> {{ message }}
                                                    </div>
                                                    </div>
                                        {% else %}
                                         <div class="flex items-center p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                        </svg>
                                        <span class="sr-only">Info</span>
                                        <div>
                                            <span class="font-medium">Success!</span> {{ message }}
                                        </div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
        <div class="w-full overflow-x-hidden border-t flex flex-col">
               <main class="w-full flex-grow p-6">

                    <div class="w-full mt-12">
                    <p class="text-xl pb-3 flex items-center">
                           <i class="fas fa-list mr-3"></i> Fill data 
                    </p>
                   
                    <div class="bg-white overflow-auto">
                          {{ form_start(form, {'attr': {'class' : 'p-10 bg-white rounded shadow-xl' }}) }}
                            <p class="text-lg text-gray-800 font-medium pb-4">Information for account: {{ account.login }}</p>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.cookies) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.event) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.date) }}
                                </div>
                              <div class="mt-2">
                                     
                                   {{ form_row(form.barcode1) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.barcode2) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.price) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.seats) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.barcode3) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.barcode4) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.price2) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.seats2) }}
                                </div>
                                 
                                 <div style = 'display:flex; justify-content: space-between;'>
                                 <div class="mt-6">
                                    <a href="{{ path('app_logged_account_cancel', {'id':account.id}) }}">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="button"> Cancel </button>
                                    </a>
                                </div> 
                                <div class="mt-6">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit"> SAVE </button>
                                </div>
                                 
                                </div>
                                {{ form_end(form) }}
                        </form>
                    </div>

               </main>
    
            <footer class="w-full bg-white text-right p-4">
                By ANCIENT STUDIO
            </footer>
        </div>
        
    </div>
    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
     
     
</body>
</html>
        {% endblock %}
         

     

 