src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: AccountRepository::class)]
#[UniqueEntity(
    fields: ['login'],
    errorPath: 'app_account_create',
    message: 'This login is already in use.',
)]
class Account
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $login = null;

    #[ORM\Column(length: 1000)]
    private ?string $password = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $cookies = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $event = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Date = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode1 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode2 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $Price = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode3 = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $barcode4 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Seats = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Price2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Seats2 = null;

    #[ORM\Column(length: 255, options: ["default" => 'Active'], nullable: true)]
    private ?string $status = null;

    #[ORM\Column(nullable: true)]
    private ?int $worker_id = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $admin_event = null;

    #[ORM\Column(nullable: true)]
    private ?int $admin_id = null;

    #[ORM\Column(nullable: true)]
    private ?float $Sell = null;

    #[ORM\Column(nullable: true)]
    private ?float $Paid = null;

    #[ORM\Column(length: 255, options: ["default" => ""] )]
    private string $createdAt;

    public function __construct()
    {
        $this->createdAt = date('Y-m-d');
    }
 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): static
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getCookies(): ?string
    {
        return $this->cookies;
    }

    public function setCookies(string $cookies): static
    {
        $this->cookies = $cookies;

        return $this;
    }

    public function getEvent(): ?string
    {
        return $this->event;
    }

    public function setEvent(string $event): static
    {
        $this->event = $event;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(?string $Date): static
    {
        $this->Date = $Date;

        return $this;
    }

    public function getBarcode1(): ?string
    {
        return $this->barcode1;
    }

    public function setBarcode1(?string $barcode1): static
    {
        $this->barcode1 = $barcode1;

        return $this;
    }

    public function getBarcode2(): ?string
    {
        return $this->barcode2;
    }

    public function setBarcode2(?string $barcode2): static
    {
        $this->barcode2 = $barcode2;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(?string $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getBarcode3(): ?string
    {
        return $this->barcode3;
    }

    public function setBarcode3(?string $barcode3): static
    {
        $this->barcode3 = $barcode3;

        return $this;
    }

    public function getBarcode4(): ?string
    {
        return $this->barcode4;
    }

    public function setBarcode4(?string $barcode4): static
    {
        $this->barcode4 = $barcode4;

        return $this;
    }

    public function getSeats(): ?string
    {
        return $this->Seats;
    }

    public function setSeats(?string $Seats): static
    {
        $this->Seats = $Seats;

        return $this;
    }

    public function getPrice2(): ?string
    {
        return $this->Price2;
    }

    public function setPrice2(?string $Price2): static
    {
        $this->Price2 = $Price2;

        return $this;
    }

    public function getSeats2(): ?string
    {
        return $this->Seats2;
    }

    public function setSeats2(?string $Seats2): static
    {
        $this->Seats2 = $Seats2;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getWorkerId(): ?int
    {
        return $this->worker_id;
    }

    public function setWorkerId(?int $worker_id): static
    {
        $this->worker_id = $worker_id;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $State): static
    {
        $this->state = $State;

        return $this;
    }

    public function getAdminEvent(): ?string
    {
        return $this->admin_event;
    }

    public function setAdminEvent(?string $admin_event): static
    {
        $this->admin_event = $admin_event;

        return $this;
    }

    public function getAdminId(): ?int
    {
        return $this->admin_id;
    }

    public function setAdminId(?int $admin_id): static
    {
        $this->admin_id = $admin_id;

        return $this;
    }

    public function getSell(): ?float
    {
        return $this->Sell;
    }

    public function setSell(?float $Sell): static
    {
        $this->Sell = $Sell;

        return $this;
    }

    public function getPaid(): ?float
    {
        return $this->Paid;
    }

    public function setPaid(?float $Paid): static
    {
        $this->Paid = $Paid;

        return $this;
    }

    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    public function setCreatedAt(string $date): static
    {
        $this->createdAt = $date;

        return $this;
    }
   
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255,options: ["default" => "/uploads/avatars/default.png"] )]
    private ?string $profile_image = null;

    #[ORM\Column(options: ["default" => 0]) ]
    private ?float $balance = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getProfileImage(): ?string
    {
        return $this->profile_image;
    }

    public function setProfileImage(string $profile_image): static
    {
        $this->profile_image = $profile_image;

        return $this;
    }

    public function getBalance(): ?int
    {
        return $this->balance;
    }
    public function updateBalance(float $balance): static
    {
        $this->balance  = $this->balance + $balance;

        return $this;
    }
 
    public function setBalance(float $balance): static
    {
        $this->balance = $balance;

        return $this;
    }
}

src/Controller/MainWorkPageController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\News;
use App\Repository\NewsRepository;
use App\Repository\AccountRepository;
 
use Doctrine\DBAL\Connection;
class MainWorkPageController extends AbstractController
{
    #[Route('/home', name: 'app_main_work_page')]
    public function index(NewsRepository $news_repository, AccountRepository $repository, Connection $conn): Response
    {
        $user = $this->getUser();

        if (!$user) {
            // Handle the case where there's no authenticated user
            return $this->redirectToRoute('login'); // Or handle it differently
        }

         

        // Query to fetch the entity with type "Admin Message" and the highest ID along with the "Text" parameter
        $adminMessage = $news_repository->GetLastAdminMessage();

        $events = $news_repository->GetLastEventMessage();
        $weeklyResults = $repository->GetGraphData($conn);
        $totalPrices = [];
        foreach ($weeklyResults as $result) {
            $totalPrices[] = $result['total_price'];
        }

        $data =  $repository->getAccountDetailsByDate($conn, date('Y-m-d'));
        $news  = ['admin'=> $adminMessage, 'events' => $events];
         
        return $this->render('main_work_page/index.html.twig', [
            'controller_name' => 'MainWorkPageController',
            'user' => $user,
            'news' =>  $news,
            "user_data" => $data,
            "graph" => $totalPrices,
            'active_page' => "News"
        ]);
    }
}

web_panel/src/Controller/MainWorkPageController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\News;
use App\Repository\NewsRepository;
 

class MainWorkPageController extends AbstractController
{
    #[Route('/home', name: 'app_main_work_page')]
    public function index(NewsRepository $news_repository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            // Handle the case where there's no authenticated user
            return $this->redirectToRoute('login'); // Or handle it differently
        }

         

        // Query to fetch the entity with type "Admin Message" and the highest ID along with the "Text" parameter
        $adminMessage = $news_repository->GetLastAdminMessage();

        $events = $news_repository->GetLastEventMessage();
         

        $news  = ['admin'=> $adminMessage, 'events' => $events];
        return $this->render('main_work_page/index.html.twig', [
            'controller_name' => 'MainWorkPageController',
            'user' => $user,
            'news' =>  $news
        ]);
    }
}

templates/main_work_page/archive.html.twig
 {% extends "main_work_page/navigation_panel.html.twig" %}
 {% block title %}Web panel{% endblock %}

{% block head %} {{parent()}}
<style> 
#example .barcode {
   
   max-width: 50px;
    
    
   overflow:hidden;
    white-space: nowrap;
   overflow-x: visible; 
 
}
 .rem89 {
    width:89rem; 
 }
#example th {
   
   width: auto;
    
     
}
</style> 

 {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
             <main class="w-full flex-grow p-6">
          
            {% for flash_type, messages in app.flashes %}
                                    {% for message in messages %}
                                    
                                        {% if flash_type =='error' %}
                                            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                                                    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                                    </svg>
                                                    <span class="sr-only">Info</span>
                                                    <div>
                                                        <span class="font-medium">&nbsp;&nbsp;Error.&nbsp;</span> {{ message }}
                                                    </div>
                                                    </div>
                                        {% else %}
                                          <div class="flex items-center p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                        </svg>
                                        <span class="sr-only">Info</span>
                                        <div>
                                            <span class="font-medium">Success!</span> {{ message }}
                                        </div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
        <div class="w-full overflow-x-hidden border-t flex flex-col">
                {% if 'ROLE_ADMIN' in app.user.roles  %}
            <button class="w-1/2 bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
                <a href="{{ path('app_archive_delete') }}"><i class="fas fa-minus mr-3"></i> Delete accounts older than one month </a>
            </button>
            {% endif %} 
                    
                <div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8 bg-dark">
    <h2 class="text-2xl font-bold mb-4">Archive</h2>
    <table id="example" class="table-auto w-full bg-dark">
        <thead>
            <tr>
                <th class="px-4 py-2" data-priority="1">Account Id</th>
                <th class="px-4 py-2" data-priority="2">Worker</th>
                <th class="px-4 py-2" data-priority="3">Sell</th>
                <th class="px-4 py-2" data-priority="4">Paid</th>
                <th class="px-4 py-2" data-priority="5">Event</th>
                <th class="px-4 py-2" data-priority="6">Seats</th>
                <th class="px-4 py-2" data-priority="7">Date</th>
                <th class="px-4 py-2" data-priority="8">Price</th>
                <th class="px-4 py-2" data-priority="9">bar1</th>
                <th class="px-4 py-2" data-priority="10">bar2</th>
                <th class="px-4 py-2" data-priority="11">Seats</th>
                <th class="px-4 py-2" data-priority="12">Price</th>
                <th class="px-4 py-2" data-priority="13">bar3</th>
                <th class="px-4 py-2" data-priority="14">bar4</th>
                <th class="px-4 py-2" data-priority="15" >Status</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
                                            <tr class="hover:bg-grey-lighter">
                                                <td class="border px-4 py-2"> {{ account.id }}</td>
                                                <td class="border px-4 py-2 hover:underline"> <a href = "{{ path('app_profile', {'id': account.workerID } ) }}"> {{ account.workerID }} </a> </td>
                                                <td class="border px-4 py-2"> {{ account.sell }} </td>
                                                <td class="border px-4 py-2"> {{ account.paid }} </td>
                                                <td class="border px-4 py-2"> {{ account.event }} </td>
                                                <td class="border px-4 py-2"> {{ account.seats }} </td>
                                                
                                                <td class="border px-4 py-2"> {{ account.date }} </td>
                                                <td class="border px-4 py-2"> {{ account.price }} </td>
                                                   <td class="border px-4 py-2 barcode"  > {{ account.barcode1 }} </td>
                                                <td class="border px-4 py-2 barcode"> {{ account.barcode2 }} </td>
                                                <td class="border px-4 py-2"> {{ account.seats2 }} </td>
                                                <td class="border px-4 py-2"> {{ account.price2 }} </td>
                                                <td class="border px-4 py-2 barcode"> {{ account.barcode3 }} </td>
                                                <td class="border px-4 py-2 barcode"> {{ account.barcode4 }} </td>
                                                {% if account.adminEvent == "Await" %}
                                                <td class="border px-4 py-2">
                                                    <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-full">
                                                        <a href="{{ path('app_check_account_by_admin',{'id': account.id }) }}">  {{ account.adminEvent }} </a>
                                                    </button>
                                                </td>
                                                {% else %}
                                                    {% if account.adminEvent == "Sold" %}
                                                    <td class="border px-4 py-2">
                                                        <button class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-4 rounded-full">
                                                            <a href="{{ path('app_check_account_by_admin',{'id': account.id }) }}">  {{ account.adminEvent }} </a>
                                                        </button>
                                                    </td>
                                                    {% else %}
                                                    <td class="border px-4 py-2">
                                                        <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full">
                                                            <a href="{{ path('app_check_account_by_admin',{'id': account.id }) }}">  {{ account.adminEvent }} </a>
                                                        </button>
                                                    </td>
                                                {% endif %}
                                             {% endif %}
                                            </tr>
            {% endfor %}
             


         
        </tbody>
    </table>
</div>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#example').DataTable({
             
            "autoWidth": false,
            "scrollX": true,
        });
    });
    function helllko () {
        $('#example').DataTable()
            .rows().invalidate('data')
            .draw(false);

    }
    $.fn.dataTable.ext.errMode = 'none';

    window.draw = helllko();
</script>
               </main>
    
            <footer class="w-full bg-white text-right p-4">
                By ANCIENT STUDIO
            </footer>
        </div>
        
    </div>
    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
     
     
</body>
</html>
        {% endblock %}
         

     

 

templates/main_work_page/logged_account.html.twig
 {% extends "main_work_page/navigation_panel.html.twig" %}
 {% block title %}Web panel{% endblock %}

{% block head %} {{parent()}} {% endblock %}
 
    {% block aside %}
    <body class="bg-gray-100 font-family-karla flex">
        {{ parent() }}
    <div class="w-full flex flex-col h-screen overflow-y-hidden">
    {% endblock %}
    
        {% block header %}
            {{ parent() }}
             {% for flash_type, messages in app.flashes %}
                                    {% for message in messages %}
                                    
                                        {% if flash_type =='error' %}
                                            <div class="flex items-center p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                                                    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                                    </svg>
                                                    <span class="sr-only">Info</span>
                                                    <div>
                                                        <span class="font-medium">&nbsp;&nbsp;Error.&nbsp;</span> {{ message }}
                                                    </div>
                                                    </div>
                                        {% else %}
                                         <div class="flex items-center p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                                        <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                        </svg>
                                        <span class="sr-only">Info</span>
                                        <div>
                                            <span class="font-medium">Success!</span> {{ message }}
                                        </div>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
        <div class="w-full overflow-x-hidden border-t flex flex-col">
               <main class="w-full flex-grow p-6">

                    <div class="w-full mt-12">
                    <p class="text-xl pb-3 flex items-center">
                           <i class="fas fa-list mr-3"></i> Fill data 
                    </p>
                    <div class="flex items-center bg-gray-200 p-4 rounded-md shadow-md">
    <!-- Page URL -->
                    <div class="flex-1 mr-4">
                        <span class="font-semibold">Page URL:</span>
                        <span id="page-url" class="block mt-1 text-blue-600 break-all">{{ app.request.uri }}</span>
                    </div>
                    <!-- Copy Button -->
                    <button id="copy-button" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Copy
                    </button>
                </div>
                    <div class="bg-white overflow-auto">
                          {{ form_start(form, {'attr': {'class' : 'p-10 bg-white rounded shadow-xl' }}) }}
                            <p class="text-lg text-gray-800 font-medium pb-4">Information for account: {{ account.login }}</p>
                            <p class="text-lg text-gray-800 font-medium pb-4">Account password: {{ account.password }}</p>    
                                <div class="mt-2">
                                     
                                   {{ form_row(form.event) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.seats) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.date) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.price) }}
                                </div>
                              <div class="mt-2">
                                     
                                   {{ form_row(form.barcode1) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.barcode2) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.seats2) }}
                                </div>
                                  <div class="mt-2">
                                     
                                   {{ form_row(form.price2) }}
                                </div>
                                 <div class="mt-2">
                                     
                                   {{ form_row(form.barcode3) }}
                                </div>
                                <div class="mt-2">
                                     
                                   {{ form_row(form.barcode4) }}
                                </div>
                                 
                                 
                                 
                                 <div style = 'display:flex; justify-content: space-between;'>
                                 <div class="mt-6">
                                    <a href="{{ path('app_logged_account_cancel', {'id':account.id}) }}">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="button"> Cancel </button>
                                    </a>
                                </div> 
                                  <div class="mt-6">
                                    <a href="{{ path('app_delete_account', {'id':account.id}) }}">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="button"> Delete </button>
                                    </a>
                                </div> 
                                <div class="mt-6">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit"> SAVE </button>
                                </div>
                                 
                                </div>
                                {{ form_end(form) }}
                        </form>
                    </div>

               </main>
    
            
        </div>
        <footer class="w-full bg-white text-right p-4">
                By ANCIENT STUDIO
            </footer>
    </div>
    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
     
    <script src= "{{ asset('assets/js/account.js') }}"></script>
</body>
</html>
        {% endblock %}
         

     

 